# Generated by Django 3.0.3 on 2020-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200702_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
